### ISSUE TITLE
DX10 refresh rate fix

### ISSUE THREAD

**Issue by vlad54rus** [ccomrade/c1-launcher#13]
Crysis 1 CryRenderD3D10.dll (32 bit 6156):
0x16F3E0 > 0F 19 00 89
Crysis 1 CryRenderD3D10.dll (64 bit 6156):
0x1C8345 > 67 0F 18 20
Posted by some dude on a Russian forum, this patch seems to make the game run at the current desktop refresh rate instead of choosing the lowest available.
Can this be added to c1-launcher?

**Comment by ccomrade** [comment]
Yes, it can be added for sure. I quickly checked what the patch does and it looks very tricky. The guy who made it has some experience with x86 assembly and D3D API for sure. Is it possible ask the guy if we can add the patch to c1-launcher? I would manually backport the patch to all game builds as usual. We also need someone to test this. My monitor seems to have only standard 60 Hz modes.

**Comment by vlad54rus** [comment]
I'll try to ask him.
Regarding your monitor - custom (resolutions) display modes can be created from the GPU control panel. Try creating second resolution with 50 Hz refresh rate.

**Comment by vlad54rus** [comment]
Ok, i've got positive reply.

**Comment by vlad54rus** [comment]
His nickname is Guzz, doesn't have a GitHub account.

**Comment by ccomrade** [comment]
The 64-bit version actually doesn't work. I'll try to fix it. The 32-bit version can be simplified. All you need to do is to put 0x909090 (3 nops) at 0x16F3E0 offset in CryRenderD3D10 DLL. It seems the guy wanted to make these patches unreadable or maybe he just used some tool that chose these weird values.

**Comment by vlad54rus** [comment]
Hmm, the 64 bit one does seem to work on my machine, as well does putting same 3 nops at 0x1C8345

**Comment by ccomrade** [comment]
The 64-bit one either has no effect (the code is not called) or it crashes (the code is called). Putting 3 nops there crashes as well. The 64-bit offset actually points to completely different location than the 32-bit one.

Anyway, I've found what exactly the working 32-bit patch does. It's actually one big nop instruction, which prevents value of `RefreshRate.Numerator` inside [DXGI_MODE_DESC](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/bb173064(v=vs.85)) from being set. The whole structure is initially filled with zeros, so `RefreshRate.Numerator` becomes zero always. Zero refresh rate means that the default refresh rate is used, which basically fixes the bug.

After some digging through the disassembly, I've also managed to find where the code is located in 64-bit version. The offset is 0x1C8F45 in 6156 build. There's only one little problem. In 64-bit code, both `Numerator` and `Denominator` are set at once with one `mov` instruction as a single 64-bit integer. Unfortunately, this makes setting `Numerator` to zero  while keeping `Denominator` value impossible. There's not enough space for such instructions. It seems that `Denominator` is always set to 1. However, according to the [documentation](https://msdn.microsoft.com/en-us/library/bb173069(v=vs.85)), when `Numerator` is set to zero, then value of `Denominator` doesn't matter at all and it can be set to zero as well. All we need is replacing that one `mov` instruction with nops. And it really works. I've also used 6 nops instead of 3 in 32-bit version to disable the second `mov`, which sets value of `Denominator`. Just to make sure that 32-bit and 64-bit versions of the patch are equal.

I've tested it on Windows 7 and it always uses the same refresh rate as configured in Windows display settings. No matter what resolutions are used on desktop and in Crysis. My [2K monitor](https://www.asus.com/Displays-Desktops/Monitors/Designo/Designo-MZ27AQ/) actually supports 75 Hz on lower resolutions and there's also additional useless 50 Hz mode in FullHD. The patch fixes 2 things here. First, that useless 50 Hz mode is not used anymore. Second, when desktop is set to lower resolution and 75 Hz, Crysis runs at 75 Hz as well if the in-game resolution allows it. This is probably the expected behavior. It would be nice if someone with 120/144/240 Hz monitor could test it too.

**Comment by vlad54rus** [comment]
Strange, but putting nops in 0x1C8F45 crashes my game, while 0x1C8345 works. Do we have the same files? My CryRenderD3D10.dll is 3 100 896 bytes, version 1.1.1.6156, CRC32 is E78B79EE,

**Comment by ccomrade** [comment]
**4** nops at 0x1C8F45 are needed. See the commit.

**Comment by ccomrade** [comment]
The file seems to be the same. You can also do right click > Properties > Digital Signatures > Crytek GmbH > Details. If it says  "This digital signature is OK.", then it's the original unmodified file.

**Comment by vlad54rus** [comment]
That's exactly what i did - 4 nops, it just crashes.

**Comment by ccomrade** [comment]
Are you sure you put those nops at the right place? The resulting absolute address should be 0x381C8F45.

**Comment by ccomrade** [comment]
You can also test the latest EXEs directly: [c1-launcher-beta-build.zip](https://github.com/ccomrade/c1-launcher/files/7498589/c1-launcher-beta-build.zip)

**Comment by vlad54rus** [comment]
Works well, thanks. Although i still don't understand why the offset is different at runtime.

**Comment by vlad54rus** [comment]
Thanks for explanation.
Any plans on porting these fixes to Crysis Warhead? And since Warheas EXE's can't be replaced - what about DLL injection?

**Comment by vlad54rus** [comment]
What about CrySystem and CryRender? I didn't mean c1-launcher specifically as patching can be done by other means, such as DLL hijacking, like SilentPatch.

**Comment by ccomrade** [comment]
Try to find the instruction. It's quite unique.

**Comment by vlad54rus** [comment]
I see that it's a single mov instruction (mov [r13+18h], rbx.
The instruction is the same between Crysis and Crysis Wars, as well as the disassembly of the function whete it is located, but i couldn't find anything simular in Crysis Warhead.

**Comment by ccomrade** [comment]
It seems D3D10 renderer is somewhat different in Crysis Warhead. I couldn't find it as well.

**Comment by vlad54rus** [comment]
Finally found it!
File offset 0x1B7FE4 > 31 C0 90 90
0x1B7FEC > 90 90 90 90

**Comment by ccomrade** [comment]
Nice

**Comment by vlad54rus** [comment]
Damn, i took the wrong 32 bit dll (687). The 711 one also has different coding, whole DXGI structures are copied with one streamed mov (rep movsd). Had to do a jump to an unused space above and do patch here.
CryRenderD3D10.dll (64 bit 711)
File offset 0x169339 > E9 B3 FE FF FF CC CC
0x1691F1 > 31 C0 89 46 08 F3 A5 5E 5F 5D 5B C3
