### ISSUE TITLE
Replace d3d10.dll/dxgi.dll absolute path with relative

### ISSUE THREAD

**Issue by vlad54rus** [ccomrade/c1-launcher#34]
CryRenderD3D10.dll loads d3d10.dll and dxgi.dll directly from C:\Windows\System32 which causes problems when using some dll wrappers such as DXVK (https://github.com/doitsujin/dxvk/issues/551#issuecomment-413019959).

**Comment by ccomrade** [comment]
This is strange because CryRenderD3D10.dll has both d3d10.dll and dxgi.dll as its dependencies (dxgi.dll indirectly via d3d10.dll):

![image](https://github.com/ccomrade/c1-launcher/assets/29867702/b9ca7144-8d29-4c43-9494-cf3370f59502)

However, it also loads them explicitly (`LoadLibraryW`) from C:\Windows\System32 (`GetSystemDirectoryW`) during startup. Any idea what could be the reason for this weird behavior? CryRenderD3D9.dll doesn't do that with its DirectX DLLs.

**Comment by vlad54rus** [comment]
Some developers do that, no idea why. But Crysis Warhead doesn't have such behavior.
I'd suggest removing GetSystemDirectoryW related code and replacing it with just LoadLibraryW("d3d10.dll") and LoadLibraryW("dxgi.dll").

**Comment by ccomrade** [comment]
Implemented. Can you test that it works with DXVK now? Here are the EXEs. Or you can take those big ones from CI/CD artifacts. I should finally implement CI/CD builds with VS2005 compiler to automatically build small EXEs as well.

[c1-launcher-v5-build.zip](https://github.com/ccomrade/c1-launcher/files/13867136/c1-launcher-v5-build.zip)

**Comment by vlad54rus** [comment]
Works great, thank you.

**Comment by ccomrade** [comment]
No problem. Thanks for the test and for reporting the issue.
