### ISSUE TITLE
Game doesn't launch

### ISSUE THREAD

**Issue by moussechoco** [ccomrade/c1-launcher#6]
Hello there. Fresh install of GOG Crysis. Just downloaded the latest release and replaced files. The game doesn't launch anymore.
It goes black screen for a while then crash to desktop. I tried with no compatibility mode and it's still the same. Did i miss something? Thanks

Ryzen 2600 for CPU
Vega64 for GPU.

**Comment by moussechoco** [comment]
Here are the last lines of the game.log if ever it's useful :

"Stream Engine Initialization
Network initialization
[net] using iocp socket io management
Physics initialization
MovieSystem initialization
Renderer initialization"

**Comment by moussechoco** [comment]
fixed. Needed to delete folders in documents. Sorry!

**Comment by ccomrade** [comment]
This happens when you launch the old version of Crysis (1.0, build 5767) and then the latest one (1.2.1, 6156). Both versions use the same `Documents/My Games/Crysis` folder by default. It seems the shader cache stored in that folder is the reason for the crash. You can edit `Game/Config/Folders.ini` to have separate folder for each version.
